### ISSUE TITLE
Fail to reproduce results in a published paper

### ISSUE THREAD

**Issue by alwaysgoodtime** [BohdanPetryshyn/code-llama-fim-fine-tuning#2] opened 2024-07-08 06:11 UTC
I try to use your hyperparameters to verify your paper, bug the result is differernt from yours. I use these hyperparameters:

  --model_name_or_path "..." \
  --dataset_file_name "..." \
  --splits "train" \
  --max_seq_len 4096 \
  --max_steps 1000 \
  --save_steps 100 \
  --eval_steps 100 \
  --logging_steps 1 \
  --log_level "info" \
  --logging_strategy "steps" \
  --evaluation_strategy "steps" \
  --save_strategy "steps" \
  --push_to_hub False \
  --bf16 False \
  --fp16 True \
  --learning_rate 2e-4 \
  --lr_scheduler_type "cosine" \
  --weight_decay 0.1 \
  --warmup_ratio 0.05 \
  --max_grad_norm 1.0 \
  --output_dir "fine-tune-19-54" \
  --per_device_train_batch_size 1 \
  --per_device_eval_batch_size 1 \
  --gradient_accumulation_steps 8 \
  --gradient_checkpointing True \
  --use_reentrant True \
  --dataset_text_field "content" \
  --test_size 0.1 \
  --fim_rate 0.9 \
  --fim_spm_rate 0.5 \
  --use_peft_lora True \
  --lora_r 32 \
  --lora_alpha 64 \
  --lora_dropout 0.1 \
  --lora_target_modules "all-linear" \
  --use_4bit_quantization True \
  --use_nested_quant True \
  --bnb_4bit_compute_dtype "bfloat16" \
  --use_flash_attn False 

If you don't mind, can you share the hyperparameters used to train the original Code-Llama?

**Comment by alwaysgoodtime** [comment] 2024-07-08 06:11
bug -> but

**Comment by BohdanPetryshyn** [comment] 2024-07-08 15:43
Hi @alwaysgoodtime 👋  Thank you for your interest in reproducing the results.

Which experiment from the paper are you trying to reproduce and what results are you getting?

I'd recommend using the notebook referenced in README.md ([link](https://colab.research.google.com/drive/1fCnfuKJHzH9afwN0vcFF75daLDtHlN26?usp=sharing)).

Here are the hyperparameters used for the "Code Llama 7B, fine-tuned with document splitting" model training:

```sh
train.py \
  --model_name_or_path codellama/CodeLlama-7b-hf \
  --dataset_name BohdanPetryshyn/openapi-completion-deduplicated \
  --splits train \
  --max_seq_len 5120 \
  --max_steps 1000 \
  --save_steps 100 \
  --eval_steps 100 \
  --logging_steps 5 \
  --log_level info \
  --logging_strategy steps \
  --evaluation_strategy steps \
  --save_strategy steps \
  --push_to_hub \
  --hub_private_repo False \
  --hub_strategy every_save \
  --bf16 True \
  --learning_rate 2e-4 \
  --lr_scheduler_type cosine \
  --weight_decay 0.1 \
  --warmup_ratio 0.05 \
  --max_grad_norm 1.0 \
  --output_dir codellama-7b-openapi-completion-ctx-lvl-fim-05-spm-doc-split-1-08-12 \
  --per_device_train_batch_size 4 \
  --per_device_eval_batch_size 4 \
  --gradient_accumulation_steps 8 \
  --gradient_checkpointing True \
  --use_reentrant True \
  --dataset_text_field content \
  --test_size 0.1 \
  --fim_rate 0.9 \
  --fim_spm_rate 0.5 \
  --use_peft_lora True \
  --lora_r 32 \
  --lora_alpha 64 \
  --lora_dropout 0.1 \
  --lora_target_modules all-linear \
  --use_4bit_quantization True \
  --use_nested_quant True \
  --bnb_4bit_compute_dtype bfloat16 \
  --use_flash_attn True
```

The adapter trained with this set of hyperparameters can be found [here](https://huggingface.co/BohdanPetryshyn/codellama-7b-openapi-completion-ctx-lvl-fim-05-spm-doc-split-1-08-12) and the merged model is available [here](https://huggingface.co/BohdanPetryshyn/codellama-7b-openapi-completion-merged-ctx-lvl-fim-05-spm-doc-split-1-08-12).

**Comment by BohdanPetryshyn** [comment] 2024-07-23 07:35
I'm closing the issue due to inactivity.

**Closed as completed by BohdanPetryshyn** 2024-07-23 07:35 UTC
